### ISSUE TITLE
Exception reported: Native is not bound 

### ISSUE THREAD

**Issue by Worco** [powerlord/sourcemod-nativevotes#2]
Greetings, i've been experiencing problems related to the following: 
![sin hhhtitulo](https://cloud.githubusercontent.com/assets/12855092/8123379/33c8e572-1096-11e5-87fa-121132272ae5.png)
This began to happen right after june 11th's tf2 update, my sourcemod's version is 1.8.0-dev+5455 and i use umc as my voting system.

Thank you for your time and effort

**Comment by powerlord** [comment]
I'm not sure what's going on here.  `GetEngineVersion` is part of the SourceMod core, but SourceMod is saying it's not loaded.

I generally don't use SourceMod 1.8.0 because it's the unstable branch... and you may get unexpected errors because of that.

As far as I can tell, NativeVotes is currently running properly on SM 1.7.3-dev+5213, which is the latest 1.7.x version.  Or at least it is on my test server, which also uses UMC.

**Comment by Worco** [comment]
Thank you, it's working now.

**Comment by powerlord** [comment]
I know this is closed, but this issue appears to be fixed in newer 1.8 versions.
